#! /usr/bin/env python3
"""A python template for plotting JV curves generated by GaussFit.
   It expects a list of files as input, which it will plot together."""

import sys
import csv
import numpy as np
from matplotlib import pyplot as plt

######################################################################
# If you want to plot R or NDC or whatever, change these labels
YLABEL = r'$log|J A cm^{-2}|$'
XLABEL = r'Potential (V)'
######################################################################


def parse(in_file):
    data = {'X': [], 'Y': [], 'Yerror': [], 'Yupper': [], 'Ylower': []}
    with open(in_file, newline="") as csvfile:
        print("Parsing %s" % in_file)
        reader = csv.reader(csvfile, dialect='JV')
        for __line in reader:
            try:
                data['X'].append(float(__line[0]))
                data['Y'].append(float(__line[1]))
                data['Yerror'].append(float(__line[2]))
                data['Yupper'].append(data['Y'][-1] + data['Yerror'][-1])
                data['Ylower'].append(data['Y'][-1] - data['Yerror'][-1])

            except ValueError:
                print("Found labels: %s" % __line)

    for key in ('X', 'Y', 'Yerror'):
        data[key] = np.array(data[key])
    return data


csv.register_dialect('JV', delimiter='\t', quoting=csv.QUOTE_MINIMAL)
datasets = []

for in_file in sys.argv[1:]:
    datasets.append(parse(in_file))


plotcolors = ('red',
              'indigo',
              'green',
              'cornflowerblue',
              'darkorange',
              'fuchsia',
              'blue'
              )

plotpoints = ('o', 's', 'd', 'v', '^', '>', '<')

label_style = {'size': 'x-large'}
plot_style = {'color': 'tab:purple', 'lw': 2.0}
major_tick_style = {'axis': 'both',
                    'which': 'major',
                    'labelsize': '14',
                    'left': True,
                    'right': True,
                    'top': True,
                    'bottom': True,
                    'direction': 'inout'}

i = 0
for data in datasets:
    plt.plot('X', 'Y', data=data, marker=plotpoints[i], color=plotcolors[i], lw=1.5)
    plt.fill_between('X', 'Ylower', 'Yupper', data=data, interpolate=True, color=plotcolors[i], alpha=0.1)
    i += 1

ax = plt.gca()

ax.legend(loc=3)
ax.set_ylabel(XLABEL, **label_style)
ax.set_xlabel(YLABEL, **label_style)

plt.rcParams["figure.figsize"] = [10.0, 6.0]
plt.tick_params(**major_tick_style)
plt.tight_layout()
plt.show()
